# Generated by Django 4.2 on 2023-06-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="main_Img",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
    ]
