# Generated by Django 4.2 on 2023-06-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0002_remove_profile_bio_remove_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="main_Img",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
