# Generated by Django 4.2 on 2023-05-05 02:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0004_bot_replies_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bot_replies",
            old_name="reply_date",
            new_name="post_date",
        ),
    ]
