# Generated by Django 4.2 on 2023-05-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0005_rename_reply_date_bot_replies_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot_replies",
            name="non_bot",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user_posts",
            name="non_bot",
            field=models.BooleanField(default=True),
        ),
    ]
