# Generated by Django 4.2 on 2023-05-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Luv", "0007_alter_bot_replies_non_bot_alter_user_posts_non_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot_replies",
            name="non_bot",
            field=models.CharField(default="bot", max_length=10),
        ),
    ]
