# Generated by Django 4.2 on 2023-05-06 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0009_characters_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bot_replies",
            options={"verbose_name_plural": "Bot_Replies"},
        ),
        migrations.AlterModelOptions(
            name="characters",
            options={"verbose_name_plural": "Characters"},
        ),
        migrations.AlterModelOptions(
            name="user_posts",
            options={"verbose_name_plural": "User_Posts"},
        ),
    ]
