# Generated by Django 4.2 on 2023-05-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0010_alter_bot_replies_options_alter_characters_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="characters",
            name="main_Img",
            field=models.ImageField(default=2, upload_to="images/"),
            preserve_default=False,
        ),
    ]
