# Generated by Django 4.2 on 2023-05-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Luv", "0011_characters_main_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characters",
            name="main_Img",
            field=models.ImageField(upload_to="img/"),
        ),
    ]
