# Generated by Django 4.2 on 2023-05-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0012_alter_characters_main_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot_replies",
            name="response_rating",
            field=models.BooleanField(default=True),
        ),
    ]
