# Generated by Django 4.2 on 2023-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Luv", "0013_bot_replies_response_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot_replies",
            name="response_rating",
            field=models.CharField(
                choices=[("GOOD", "Good"), ("BAD", "Bad")], default="GOOD", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="user_posts",
            name="message",
            field=models.TextField(max_length=400),
        ),
    ]
