# Generated by Django 4.2 on 2023-05-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0014_alter_bot_replies_response_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot_replies",
            name="response_rating",
            field=models.CharField(default="Good", max_length=4),
        ),
    ]
