# Generated by Django 4.2 on 2023-06-20 05:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0016_categories_characters_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
