# Generated by Django 4.2 on 2023-06-23 05:42

import Luv.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0017_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characters",
            name="main_Img",
            field=models.ImageField(
                upload_to="img/", validators=[Luv.validators.validate_file_size]
            ),
        ),
    ]
