# Generated by Django 4.2 on 2023-07-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Luv", "0018_alter_characters_main_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="characters",
            name="tagline",
            field=models.CharField(default="hey whats up", max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="characters",
            name="description",
            field=models.CharField(max_length=10000),
        ),
    ]
